### ISSUE TITLE
截图到第30页，出现bug

### ISSUE THREAD

**Issue by RessMatthew** [Qalxry/WQBookDownloader#1]
<img width="1060" alt="image" src="https://github.com/user-attachments/assets/70acac8c-9c44-428c-a8be-dce7436e6ba0">

PS：本人未购买书籍，是登入学校机构账号。

**Comment by Qalxry** [comment]
你好，没想到这么快就有人用了这个仓库😂

30页是因为文泉书局对于付费书籍只开放前30页的预览，如果没有购买的话只能下载前30页。

**Comment by RessMatthew** [comment]
你好，友友好快的回复。
我们学校机构账号是可以看到完整电子书的，如下图：
<img width="1533" alt="image" src="https://github.com/user-attachments/assets/41267ce1-5310-4d7c-830c-d6ec78783b65">

PS：我想下载的图书是 bid 是 3251197，看了在线预览书籍的url包含学校缩写，怀疑可能url需要修改。谢谢解答🙏

**Comment by RessMatthew** [comment]
兄弟，已经解决啦，就是改改URL的事，感谢。
挺不错的代码。

**Comment by Qalxry** [comment]
OK，感谢提供解决方案，很高兴代码能够用上😁

**Comment by cxhagd** [comment]
![image](https://github.com/user-attachments/assets/92732744-a1c1-43a6-a0e2-b8e681edce67)
您好，我需要下载的书的url不包含学校缩写，但仍然只能截图截到30页
![image](https://github.com/user-attachments/assets/5143b85b-8138-4d52-9c92-86f508e76ba9)

**Comment by cxhagd** [comment]
应该是我没有买这个书，没事了。
