### ISSUE TITLE
在线阅读器界面元素变动 （2024年11月7日）

### ISSUE THREAD

**Issue by LadderOperator** [Qalxry/WQBookDownloader#3]
https://github.com/Qalxry/WQBookDownloader/blob/2135eeb5e872569b2a061ecb2ecffb009809a1b6/WQBookDownloader.js#L247C1-L247C84

以防有人搜到这儿：2024年11月7日阅读器界面元素变了，现在需要更新为：

```javascript
await page.waitForSelector(`#pageImgBox${pageNum} uni-view.page-lmg img`);
```

顺便吐槽下，注意这里是`page-lmg`（小写L）不是`page-Img`（大写i）

**Comment by Qalxry** [comment]
非常感谢！已将此更新到代码中！[Commit cc80f37
](https://github.com/Qalxry/WQBookDownloader/commit/cc80f377819d0c7fcad68f4b2a71558ad5443412)
